-- J.A.R.V.I.S. #3 — Timers & Reminders
-- Run this once in Supabase SQL Editor.

create table if not exists public.timers_reminders (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    type text not null check (type in ('timer', 'reminder')),
    title text not null default 'Reminder',
    due_at timestamptz not null,
    status text not null default 'active'
        check (status in ('active', 'paused', 'triggered', 'cancelled')),
    repeat_rule text null,
    duration_seconds integer null,
    remaining_seconds integer null,
    last_triggered_at timestamptz null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_timers_reminders_user_status_due
    on public.timers_reminders (user_id, status, due_at);

create index if not exists idx_timers_reminders_user_triggered
    on public.timers_reminders (user_id, status, last_triggered_at);

-- The JARVIS backend currently uses SUPABASE_SERVICE_KEY.
-- That server-side key bypasses RLS, while user_id still isolates
-- records at the application layer.
alter table public.timers_reminders enable row level security;

-- Optional trigger to keep updated_at current when records are edited.
create or replace function public.set_timers_reminders_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists timers_reminders_updated_at
on public.timers_reminders;

create trigger timers_reminders_updated_at
before update on public.timers_reminders
for each row
execute function public.set_timers_reminders_updated_at();
